# ОСНОВНОЕ
foreground            #ffffff
background            #000000
background_opacity    0.6
dynamic_background_opacity yes

# КУРСОР И ВЫДЕЛЕНИЕ (Серый неон)
cursor                #ffffff
selection_background  #444444
selection_foreground  #ffffff

# ТАБЛИЦА ЦВЕТОВ (ТОЛЬКО ЧЕРНЫЙ, БЕЛЫЙ И СЕРЫЙ)
# Это уберет синеву из neofetch и других команд

# Black
color0  #000000
color8  #444444

# Red -> Gray
color1  #666666
color9  #888888

# Green -> White
color2  #eeeeee
color10 #ffffff

# Yellow -> Gray
color3  #999999
color11 #aaaaaa

# Blue -> Gray/White
color4  #bbbbbb
color12 #dddddd

# Magenta -> White
color5  #eeeeee
color13 #ffffff

# Cyan -> Gray
color6  #cccccc
color14 #eeeeee

# White
color7  #dddddd
color15 #ffffff
